apiVersion: apps/v1
kind: Deployment
metadata:
    name: employee-app-deployment
    namespace: public-dikshasingla
    labels:
        app: employee-app
spec:
    replicas: 3
    selector:
        matchLabels:
            app: employee-app
    template:
        metadata:
            labels:
                app: employee-app
        spec:
            containers:
                - name: employee-app
                  image: dikshasingla/employee:1
                  ports:
                    - name: http
                      containerPort: 3515
                      protocol: TCP
                  env:
                    - name: MONGO_USERNAME
                      valueFrom:
                        secretKeyRef:
                            name: mongodb-secret
                            key: username
                    - name: MONGO_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: mongodb-secret
                            key: password
                    - name: MONGO_HOST_NAME
                      valueFrom:
                        configMapKeyRef:
                            name: mongodb-configmap
                            key: database_service