apiVersion: v1
kind: Service
metadata: 
    name: employee-app
    namespace: public-dikshasingla
    labels:
        app: employee-app
spec:
    type: LoadBalancer
    selector:
        app: employee-app
    ports:
        - protocol: TCP
          nodePort: 30157
          port: 80
          targetPort: 3515